GUA-23 Update changeset check rule to fail if no changeset

diff --git a/.github/workflows/changeset-exists.yml b/.github/workflows/changeset-exists.yml
--- a/.github/workflows/changeset-exists.yml
+++ b/.github/workflows/changeset-exists.yml
@@ -27,9 +27,16 @@ jobs:
         id: changed-files
         uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
 
-      - name: List all added files
+      - name: Pass if changeset file is added
         env:
           ADDED_FILES: ${{ steps.changed-files.outputs.added_files }}
         if: contains(steps.changed-files.outputs.added_files, '.changeset/' )
         run: echo "Changeset file added"
 
+      - name: Fail if no changeset file is added
+        env:
+          ADDED_FILES: ${{ steps.changed-files.outputs.added_files }}
+        if: !contains(steps.changed-files.outputs.added_files , '.changeset/' )
+        run: |
+          echo "Error: No changeset file added. Please add a changeset file in the .changeset/ directory."
+          exit 1
